import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body  className="bg-black text-gray-400 ">
        <div className='flex items-center justify-center bg-slate-200'>

        <Header />
        </div>
        {children}
        <Footer/>
       
       
        </body>
    </html>
  )
}
